# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

# Flex environment
runtime: java17
instance_class: F2

# Fixed number of instances
#runtime: java
#env: flex
#
#automatic_scaling:
#     max_num_instances: 1
#
#runtime_config:
#    operating_system: "ubuntu22"
#    runtime_version: "17"